### ISSUE TITLE
Is this compatible with auditwheel?

### ISSUE THREAD

**Issue by thomascobb** [mdavidsaver/setuptools_dso#17]
I'm trying to use cibuildwheel to make wheels for pythonIoc compiled against epicscorelibs. It seems to want to run auditwheel by default: https://cibuildwheel.readthedocs.io/en/stable/options/#repair-wheel-command but this fails with
```sh -c 'auditwheel repair -w /tmp/cibuildwheel/repaired_wheel /tmp/cibuildwheel/built_wheel/softioc-0.0+untagged.g5625753-cp27-cp27m-linux_x86_64.whl'
  INFO:auditwheel.main_repair:Repairing softioc-0.0+untagged.g5625753-cp27-cp27m-linux_x86_64.whl
  Traceback (most recent call last):
    File "/usr/local/bin/auditwheel", line 8, in <module>
      sys.exit(main())
    File "/opt/_internal/tools/lib/python3.7/site-packages/auditwheel/main.py", line 50, in main
      rval = args.func(args, p)
    File "/opt/_internal/tools/lib/python3.7/site-packages/auditwheel/main_repair.py", line 95, in execute
      strip=args.STRIP)
    File "/opt/_internal/tools/lib/python3.7/site-packages/auditwheel/repair.py", line 69, in repair_wheel
      soname)
  ValueError: Cannot repair wheel, because required library "libdbCore.so.7.0.4.99.1" could not be located
```

Is this expected? Should I just skip the auditwheel stage?

**Comment by mdavidsaver** [comment]
> Is this expected?

Yes.  auditwheel has no concept of looking for library dependencies in other python modules.

> Should I just skip the auditwheel stage?

I think this will be necessary.  There doesn't seem to be any configuration for auditwheel at all, so I don't think it is possible to have it ignore certain libraries/packages, or to treat "missing" libraries as warnings.

**Comment by thomascobb** [comment]
Sounds reasonable, all the lib dependencies are managed by setuptools_dso, so I shouldn't need auditwheel at all...
