### ISSUE TITLE
Error when package name has no .

### ISSUE THREAD

**Issue by hhslepicka** [mdavidsaver/setuptools_dso#4]
I came across this while trying to use `setuptools_dso` for a package.
Here are the output with the error and the setup.py files:
https://gist.github.com/hhslepicka/f24bf58e2b754bfb05ac53e06d50145f

If I change the Extension name to be: `.pyca` I get the expected result and all works fine.

**Comment by mdavidsaver** [comment]
Should be fixed by 5c42c1baa321838bcf57fa16d260be8a0881f298

**Comment by hhslepicka** [comment]
I will give it a try. Thank you for looking into it.
